mediascape/old/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('',                    ['as' => 'frontend.home',             'uses' => 'WebPage\WebPageController@index']);
Route::get('home',                    ['as' => 'frontend.home',             'uses' => 'WebPage\WebPageController@index']);
Route::get('about-us',                    ['as' => 'frontend.about-us',             'uses' => 'WebPage\WebPageController@about']);
Route::get('contact-us',                    ['as' => 'frontend.contact-us',             'uses' => 'WebPage\WebPageController@contact']);
Route::get('portfolio',                    ['as' => 'frontend.portfolio',             'uses' => 'WebPage\WebPageController@portflio']);
Route::post('onlineorder',                    ['as' => 'frontend.onlineorder',             'uses' => 'WebPage\WebPageController@onlineorder']);
Route::get('services/',                    ['as' => 'frontend.services',             'uses' => 'WebPage\WebPageController@action']);
Route::get('services/{slug}',                    ['as' => 'frontend.service',             'uses' => 'WebPage\WebPageController@action']);
Route::get('our-team/{slug}',                    ['as' => 'frontend.ourteams',             'uses' => 'WebPage\WebPageController@ourteam']);
Route::get('our-team',                    ['as' => 'frontend.our-team',             'uses' => 'WebPage\WebPageController@ourteam']);

Auth::routes();

Route::get('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout' ]);

//Route::get('/', function () {
//    return redirect('login');
//});

/*Route::get('/home', function () {
    return redirect()->route('admin.listing.index');
});*/

Route::group(['middleware' => ['auth', 'status'], 'prefix' => '', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {

    Route::get('admin/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('admin/error/{code}',                        ['as' => 'error',                 'uses' => 'DashboardController@error']);

    Route::get('admin/profile/setting', ['as' => 'profile.setting', 'uses' => 'ProfileController@index']);
    Route::post('admin/profile/updatePassword/{id}', ['as' => 'profile.updatePassword', 'uses' => 'ProfileController@updatePassword']);

    Route::get('admin/profile', ['as' => 'profile', 'uses' => 'ProfileController@edit']);
    Route::post('admin/profile/{id}/update', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);

    Route::get('admin/feedback',['as' => 'feedback.list', 'uses' => 'FeedbackController@index']);
    Route::get('admin/feedback/{id}/update',          ['as' => 'feedback.update',          'uses' => 'FeedbackController@update']);

    Route::get('admin/about-us',                        ['as' => 'about-us.index',           'uses' => 'AboutUsController@index']);
    Route::get('admin/about-us/add',                    ['as' => 'about-us.add',             'uses' => 'AboutUsController@add']);
    Route::post('admin/about-us/store',                 ['as' => 'about-us.store',           'uses' => 'AboutUsController@store']);
    Route::get('admin/about-us/{id}/edit',              ['as' => 'about-us.edit',            'uses' => 'AboutUsController@edit']);
    Route::post('admin/about-us/{id}/update',          ['as' => 'about-us.update',          'uses' => 'AboutUsController@update']);
    Route::get('admin/about-us/{id}/delete',           ['as' => 'about-us.delete',          'uses' => 'AboutUsController@delete']);

    Route::get('admin/gallery',                        ['as' => 'gallery.index',           'uses' => 'GalleryController@index']);
    Route::get('admin/gallery/add',                    ['as' => 'gallery.add',             'uses' => 'GalleryController@add']);
    Route::post('admin/gallery/store',                 ['as' => 'gallery.store',           'uses' => 'GalleryController@store']);
    Route::get('admin/gallery/{id}/edit',              ['as' => 'gallery.edit',            'uses' => 'GalleryController@edit']);
    Route::post('admin/gallery/{id}/update',          ['as' => 'gallery.update',          'uses' => 'GalleryController@update']);
    Route::get('admin/gallery/{id}/delete',           ['as' => 'gallery.delete',          'uses' => 'GalleryController@delete']);

    Route::get('admin/banner',                        ['as' => 'banner.index',           'uses' => 'BannerController@index']);
    Route::get('admin/banner/add',                    ['as' => 'banner.add',             'uses' => 'BannerController@add']);
    Route::post('admin/banner/store',                 ['as' => 'banner.store',           'uses' => 'BannerController@store']);
    Route::get('admin/banner/{id}/edit',              ['as' => 'banner.edit',            'uses' => 'BannerController@edit']);
    Route::post('admin/banner/{id}/update',          ['as' => 'banner.update',          'uses' => 'BannerController@update']);
    Route::get('admin/banner/{id}/delete',           ['as' => 'banner.delete',          'uses' => 'BannerController@delete']);

    Route::get('admin/services',                        ['as' => 'services.index',           'uses' => 'ServicesController@index']);
    Route::get('admin/services/add',                    ['as' => 'services.add',             'uses' => 'ServicesController@add']);
    Route::post('admin/services/store',                 ['as' => 'services.store',           'uses' => 'ServicesController@store']);
    Route::get('admin/services/{id}/edit',              ['as' => 'services.edit',            'uses' => 'ServicesController@edit']);
    Route::post('admin/services/{id}/update',          ['as' => 'services.update',          'uses' => 'ServicesController@update']);
    Route::get('admin/services/{id}/delete',           ['as' => 'services.delete',          'uses' => 'ServicesController@delete']);

    Route::get('admin/contact',                        ['as' => 'contact.index',           'uses' => 'ContactController@index']);
    Route::get('admin/contact/add',                    ['as' => 'contact.add',             'uses' => 'ContactController@add']);
    Route::post('admin/contact/store',                 ['as' => 'contact.store',           'uses' => 'ContactController@store']);
    Route::get('admin/contact/{id}/edit',              ['as' => 'contact.edit',            'uses' => 'ContactController@edit']);
    Route::post('admin/contact/{id}/update',          ['as' => 'contact.update',          'uses' => 'ContactController@update']);
    Route::get('admin/contact/{id}/delete',           ['as' => 'contact.delete',          'uses' => 'ContactController@delete']);

    Route::get('admin/pakage',                        ['as' => 'pakage.index',           'uses' => 'PakageController@index']);
    Route::get('admin/pakage/add',                    ['as' => 'pakage.add',             'uses' => 'PakageController@add']);
    Route::post('admin/pakage/store',                 ['as' => 'pakage.store',           'uses' => 'PakageController@store']);
    Route::get('admin/pakage/{id}/edit',              ['as' => 'pakage.edit',            'uses' => 'PakageController@edit']);
    Route::post('admin/pakage/{id}/update',          ['as' => 'pakage.update',          'uses' => 'PakageController@update']);
    Route::get('admin/pakage/{id}/delete',           ['as' => 'pakage.delete',          'uses' => 'PakageController@delete']);

    Route::get('admin/onlineorder/{id}/reply',                    ['as' => 'onlineorder.reply',             'uses' => 'OnlineorderController@reply']);
    Route::post('admin/onlineorder/{id}/mail',                 ['as' => 'onlineorder.mail',           'uses' => 'OnlineorderController@mail']);
    Route::get('admin/onlineorder/{id}/edit',              ['as' => 'onlineorder.edit',            'uses' => 'OnlineorderController@edit']);
    Route::get('admin/onlineorder',                        ['as' => 'onlineorder.index',           'uses' => 'OnlineorderController@index']);
    Route::get('admin/onlineorder/{id}/update', ['as' => 'onlineorder.update', 'uses' => 'OnlineorderController@update']);
    Route::get('admin/onlineorder/{id}/delete',           ['as' => 'onlineorder.delete',          'uses' => 'OnlineorderController@delete']);

    Route::get('admin/menu',                        ['as' => 'menu.index',           'uses' => 'MenuController@index']);
    Route::post('admin/menu/search',                        ['as' => 'menu.search',           'uses' => 'MenuController@search']);
    Route::get('admin/menu/add',                    ['as' => 'menu.add',             'uses' => 'MenuController@add']);
    Route::post('admin/menu/store',                 ['as' => 'menu.store',           'uses' => 'MenuController@store']);
    Route::get('admin/menu/{id}/edit',              ['as' => 'menu.edit',            'uses' => 'MenuController@edit']);
    Route::post('admin/menu/{id}/update',          ['as' => 'menu.update',          'uses' => 'MenuController@update']);
    Route::get('admin/menu/{id}/delete',           ['as' => 'menu.delete',          'uses' => 'MenuController@delete']);
    Route::get('admin/menu/{slug}',           ['as' => 'admin.menu',          'uses' => 'MenuController@menu']);
    Route::get('admin/menu/submenu/{slug}',           ['as' => 'admin.menu.submenu',          'uses' => 'MenuController@menuSubmenu']);

    Route::get('admin/page',                        ['as' => 'page.index',           'uses' => 'PageController@index']);
    Route::get('admin/page/add',                    ['as' => 'page.add',             'uses' => 'PageController@add']);

mediascape/old/app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $table = 'photo';

    // protected $timestamp = false;

    protected $guarded = [];

    protected $fillable = ['title', 'image', 'gallery_id', 'description', 'status'];




}

mediascape/old/app/Http/Controllers/Admin/PhotoController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 11/15/16
 * Time: 7:29 AM
 */
namespace App\Http\Controllers\Admin;
use App\Http\Requests\Photo\AddValidation;
use App\Models\Gallery;
use App\Models\Photo;
use Illuminate\Http\Request;


class PhotoController extends AdminBaseController
{
    protected $base_route = 'admin.photo';
    protected $view_path = 'admin.photo';
    protected $view_title = 'Photo Manger';
    protected $folder_name = 'photo';
    protected $trans_path = '';
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path().DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR.$this->folder_name.DIRECTORY_SEPARATOR;
    }


    public function index(Request $request)
    {
        $data = [];
        $data['rows'] = Photo::select('id','title', 'image', 'description', 'status')
            ->orderBy('id')
            ->paginate(30);
        $data['group'] = Gallery::select('id')->get();

        return view(parent::loadDefaultVars($this->view_path.'.list'), compact('data'));
    }

    public function add(Request $request)
    {

        $data = [];
        $data['gallery'] = Gallery::select('id','title')->get();
        return view(parent::loadDefaultVars($this->view_path.'.add'), compact('data'));
    }

    public function store(AddValidation $request)
    {
        if ($request->hasFile('image')){
            $image = $request->file('image');
            $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
            $image->move($this->folder_path,$file_name);
        }

       $list = Photo::create([
           'title'               =>     $request->get('title'),
           'image'                =>    $file_name,
           'gallery_id' => $request->get('gallery_id'),
           'description' => $request->get('description'),
           'status' => $request->get('status'),
        ]);

        $request->session()->flash('message', 'Photo added successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function edit(Request $request, $id)
    {
        // get user data for $id
        //dd($id);
        $data = [];

        $data['gallery'] = Gallery::select('id','title')->get();
        if (!$data['row'] = Photo::find($id))
            return redirect()->route('admin.error', ['code' => '500']);
        $data['row'] = Photo::find($id);

        return view(parent::loadDefaultVars($this->view_path.'.edit'), compact('data'));
    }

    public function update(EditValidation $request, $id)
    {

        if ($request->hasFile('image')){
            $image = $request->file('image');
            $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
            $image->move($this->folder_path,$file_name);
        }else{
            $file_name = $request->get('oldimg');
        }

        if (!$listing = Photo::find($id))
            return redirect()->route('admin.error', ['code' => '500']);


        $listing->update([
            'title'               =>     $request->get('title'),
            'image'                =>    $file_name,
            'status' => $request->get('status'),
        ]);




        $request->session()->flash('message', 'Photo updated successfully.');
        return redirect()->route($this->base_route.'.index');
    }

    public function delete(Request $request, $id)
    {
       //dd('enter');
        if (!$listing = Photo::find($id))
            return redirect()->route('admin.error', ['code' => '500']);

        // remove image before deleting db row

        $listing->delete();
        $request->session()->flash('message', 'Photo deleted successfully.');
        return redirect()->route($this->base_route.'.index');
    }



}

mediascape/old/resources/views/admin/photo/add.blade.php
@extends('admin.common.layout.layout')

@section('page_title'){{ $view_title }} - {{ trans('general.admin_panel') }} @endsection

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            @include($view_path.'partials.breadcrumb')
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ $view_title }}<small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'content.add.add_form') }}</small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    <form id="listing-form" class="form-horizontal" role="form" method="POST" action="{{ route($base_route.'.store') }}" enctype="multipart/form-data">

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">


                        @if(isset($data['row']))
                            {{ dd($data['row']) }}
                            @endif

                        @include($view_path.'partials.form')

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button id="form-submit-btn" class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i>
                                    {{ trans('general.button.submit') }}
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="icon-undo bigger-110"></i>
                                    {{ trans('general.button.reset') }}
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>



                    </form>


                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>

    @endsection

@section('page_specific_scripts')

    @include($view_path.'.partials.add.jquery-validation-scripts')

    @endsection

mediascape/old/resources/views/admin/photo/edit.blade.php
@extends('admin.common.layout.layout')

@section('page_title'){{ $view_title }} - {{ trans('general.admin_panel') }} @endsection

@section('content')

    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            @include($view_path.'partials.breadcrumb')

        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ $view_title }}<small>
                        <i class="icon-double-angle-right"></i>
                        Edit</small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    <form class="form-horizontal" role="form" method="POST" action="{{ route($base_route.'.update', ['id' => $data['row']->id]) }}" enctype="multipart/form-data">

                        <input type="hidden" name="_token" value="{{ csrf_token() }}">


                        @include($view_path.'partials.form')

                        <div class="clearfix form-actions">
                            <div class="col-md-offset-3 col-md-9">
                                <button class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i>
                                    {{ trans('general.button.update') }}
                                </button>

                                &nbsp; &nbsp; &nbsp;
                                <button class="btn" type="reset">
                                    <i class="icon-undo bigger-110"></i>
                                    {{ trans('general.button.reset') }}
                                </button>
                            </div>
                        </div>

                        <div class="hr hr-24"></div>



                    </form>


                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>

    @endsection
@section('page_specific_scripts')

    @include($view_path.'.partials.add.jquery-validation-scripts')

@endsection

mediascape/old/resources/views/admin/photo/list.blade.php
@extends('admin.common.layout.layout')

@section('page_title'){{ $view_title }} - {{ trans('general.admin_panel') }} @endsection

@section('content')


    <div class="main-content">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
            </script>

            @include($view_path.'.partials.breadcrumb')

            <div class="nav-search" id="nav-search">
                <form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off">
									<i class="icon-search nav-search-icon"></i>
								</span>
                </form>
            </div><!-- #nav-search -->
        </div>

        <div class="page-content">
            <div class="page-header">
                <h1>
                    {{ $view_title }}
                    <small>
                        <i class="icon-double-angle-right"></i>
                        {{ trans($trans_path.'content.list.list') }}
                    </small>
                </h1>
            </div><!-- /.page-header -->

            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->

                    <div class="row">
                        <div class="col-xs-12">
                            <div class="table-responsive">

                                @if (Request::session()->has('message'))
                                    <div class="alert alert-info">
                                        <button type="button" class="close" data-dismiss="alert">
                                            <i class="icon-remove"></i>
                                        </button>
                                        {!! Request::session()->get('message') !!}
                                        <br>
                                    </div>
                                @endif

                                <table id="sample-table-1" class="table table-striped table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th class="center">
                                            sn
                                        </th>
                                        <th>Name</th>
                                        <th>Image</th>
                                        <th>Discription</th>
                                        <th>status</th>
                                        <th></th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @if ($data['rows']->count() > 0)
                                        <tr id="search_div">
                                            <td></td>
                                            <td><input type="text" id="search_name"></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                        </tr>
                                        @php $counter=0; @endphp
                                        @foreach($data['rows'] as $row)
                                            @php $counter++ @endphp

                                            <tr>

                                                <td class="center">
                                                    {{ $counter }}
                                                </td>

                                                <td>
                                                   {{ $row->title }}
                                                </td>
                                                <td>
                                                    <img src="{{ asset('images/photo/'.$row->image) }}" width="200px" alt="">
                                                </td>

                                                <td>{{ $row->description }}</td>

                                                <td>
                                                    @if ($row->status == 1)
                                                        Active
                                                    @else
                                                        InActive
                                                    @endif
                                                </td>



                                            @if(Auth::user()->type=="admin")
                                                <td>
                                                    <div class="btn-group">

                                                        <a class="btn btn-xs btn-info" href="{{ route($base_route.'.edit', ['id' => $row->id]) }}">
                                                            <i class="icon-edit bigger-120"></i>
                                                        </a>



                                                    </div>

                                                    <div class="btn-group">

                                                        <a href="{{ route($base_route.'.delete', $row->id) }}"  class="btn btn-xs btn-danger bootbox-confirm">
                                                            <i class="icon-trash bigger-120"></i>
                                                        </a>



                                                    </div>


                                                </td>
                                                @endif
                                            </tr>

                                            @endforeach

                                        @else

                                        <tr>
                                            <td colspan="7">No data found.</td>
                                        </tr>

                                        @endif

                                    </tbody>
                                </table>
                            </div>
                            <div class="col-xs-4">
                        {{ $data['rows']->links() }}
                            </div>

                            <!-- /.table-responsive -->
                        </div><!-- /span -->
                    </div><!-- /row -->

                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>

    @endsection

@section('page_specific_scripts')

    <script src="{{ asset('assets/admin/js/bootbox.min.js') }}"></script>
    <script>
        $(".bootbox-confirm").on(ace.click_event, function() {
            console.log('sdfd');
            bootbox.confirm("Are you sure?", function(result) {
                if(result) {
                    //
                }
            });
        });
    </script>
    <script>

        $(document).ready(function () {
           $('#search_name').change(function () {

               var name = $('#search_name').val();

               var url = '{{ route('admin.gallery.index') }}';

               $.ajax({
                   url: url,
                   method

               });

           });
        });

    </script>


@endsection