mediascape/old/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('',                    ['as' => 'frontend.home',             'uses' => 'WebPage\WebPageController@index']);
Route::get('home',                    ['as' => 'frontend.home',             'uses' => 'WebPage\WebPageController@index']);
Route::get('about-us',                    ['as' => 'frontend.about-us',             'uses' => 'WebPage\WebPageController@about']);
Route::get('contact-us',                    ['as' => 'frontend.contact-us',             'uses' => 'WebPage\WebPageController@contact']);
Route::get('portfolio',                    ['as' => 'frontend.portfolio',             'uses' => 'WebPage\WebPageController@portflio']);
Route::post('onlineorder',                    ['as' => 'frontend.onlineorder',             'uses' => 'WebPage\WebPageController@onlineorder']);
Route::get('services/',                    ['as' => 'frontend.services',             'uses' => 'WebPage\WebPageController@action']);
Route::get('services/{slug}',                    ['as' => 'frontend.service',             'uses' => 'WebPage\WebPageController@action']);
Route::get('our-team/{slug}',                    ['as' => 'frontend.ourteams',             'uses' => 'WebPage\WebPageController@ourteam']);
Route::get('our-team',                    ['as' => 'frontend.our-team',             'uses' => 'WebPage\WebPageController@ourteam']);

Auth::routes();

Route::get('logout', [ 'as' => 'logout', 'uses' => 'Auth\LoginController@logout' ]);

//Route::get('/', function () {
//    return redirect('login');
//});

/*Route::get('/home', function () {
    return redirect()->route('admin.listing.index');
});*/

Route::group(['middleware' => ['auth', 'status'], 'prefix' => '', 'as' => 'admin.', 'namespace' => 'Admin\\'], function () {

    Route::get('admin/dashboard', ['as' => 'dashboard', 'uses' => 'DashboardController@index']);
    Route::get('admin/error/{code}',                        ['as' => 'error',                 'uses' => 'DashboardController@error']);

    Route::get('admin/profile/setting', ['as' => 'profile.setting', 'uses' => 'ProfileController@index']);
    Route::post('admin/profile/updatePassword/{id}', ['as' => 'profile.updatePassword', 'uses' => 'ProfileController@updatePassword']);

    Route::get('admin/profile', ['as' => 'profile', 'uses' => 'ProfileController@edit']);
    Route::post('admin/profile/{id}/update', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);

    Route::get('admin/feedback',['as' => 'feedback.list', 'uses' => 'FeedbackController@index']);
    Route::get('admin/feedback/{id}/update',          ['as' => 'feedback.update',          'uses' => 'FeedbackController@update']);

    Route::get('admin/about-us',                        ['as' => 'about-us.index',           'uses' => 'AboutUsController@index']);
    Route::get('admin/about-us/add',                    ['as' => 'about-us.add',             'uses' => 'AboutUsController@add']);
    Route::post('admin/about-us/store',                 ['as' => 'about-us.store',           'uses' => 'AboutUsController@store']);
    Route::get('admin/about-us/{id}/edit',              ['as' => 'about-us.edit',            'uses' => 'AboutUsController@edit']);
    Route::post('admin/about-us/{id}/update',          ['as' => 'about-us.update',          'uses' => 'AboutUsController@update']);
    Route::get('admin/about-us/{id}/delete',           ['as' => 'about-us.delete',          'uses' => 'AboutUsController@delete']);

    Route::get('admin/gallery',                        ['as' => 'gallery.index',           'uses' => 'GalleryController@index']);
    Route::get('admin/gallery/add',                    ['as' => 'gallery.add',             'uses' => 'GalleryController@add']);
    Route::post('admin/gallery/store',                 ['as' => 'gallery.store',           'uses' => 'GalleryController@store']);
    Route::get('admin/gallery/{id}/edit',              ['as' => 'gallery.edit',            'uses' => 'GalleryController@edit']);
    Route::post('admin/gallery/{id}/update',          ['as' => 'gallery.update',          'uses' => 'GalleryController@update']);
    Route::get('admin/gallery/{id}/delete',           ['as' => 'gallery.delete',          'uses' => 'GalleryController@delete']);

    Route::get('admin/banner',                        ['as' => 'banner.index',           'uses' => 'BannerController@index']);
    Route::get('admin/banner/add',                    ['as' => 'banner.add',             'uses' => 'BannerController@add']);
    Route::post('admin/banner/store',                 ['as' => 'banner.store',           'uses' => 'BannerController@store']);
    Route::get('admin/banner/{id}/edit',              ['as' => 'banner.edit',            'uses' => 'BannerController@edit']);
    Route::post('admin/banner/{id}/update',          ['as' => 'banner.update',          'uses' => 'BannerController@update']);
    Route::get('admin/banner/{id}/delete',           ['as' => 'banner.delete',          'uses' => 'BannerController@delete']);

    Route::get('admin/services',                        ['as' => 'services.index',           'uses' => 'ServicesController@index']);
    Route::get('admin/services/add',                    ['as' => 'services.add',             'uses' => 'ServicesController@add']);
    Route::post('admin/services/store',                 ['as' => 'services.store',           'uses' => 'ServicesController@store']);
    Route::get('admin/services/{id}/edit',              ['as' => 'services.edit',            'uses' => 'ServicesController@edit']);
    Route::post('admin/services/{id}/update',          ['as' => 'services.update',          'uses' => 'ServicesController@update']);
    Route::get('admin/services/{id}/delete',           ['as' => 'services.delete',          'uses' => 'ServicesController@delete']);

    Route::get('admin/contact',                        ['as' => 'contact.index',           'uses' => 'ContactController@index']);
    Route::get('admin/contact/add',                    ['as' => 'contact.add',             'uses' => 'ContactController@add']);
    Route::post('admin/contact/store',                 ['as' => 'contact.store',           'uses' => 'ContactController@store']);
    Route::get('admin/contact/{id}/edit',              ['as' => 'contact.edit',            'uses' => 'ContactController@edit']);
    Route::post('admin/contact/{id}/update',          ['as' => 'contact.update',          'uses' => 'ContactController@update']);
    Route::get('admin/contact/{id}/delete',           ['as' => 'contact.delete',          'uses' => 'ContactController@delete']);

    Route::get('admin/pakage',                        ['as' => 'pakage.index',           'uses' => 'PakageController@index']);
    Route::get('admin/pakage/add',                    ['as' => 'pakage.add',             'uses' => 'PakageController@add']);
    Route::post('admin/pakage/store',                 ['as' => 'pakage.store',           'uses' => 'PakageController@store']);
    Route::get('admin/pakage/{id}/edit',              ['as' => 'pakage.edit',            'uses' => 'PakageController@edit']);
    Route::post('admin/pakage/{id}/update',          ['as' => 'pakage.update',          'uses' => 'PakageController@update']);
    Route::get('admin/pakage/{id}/delete',           ['as' => 'pakage.delete',          'uses' => 'PakageController@delete']);

    Route::get('admin/onlineorder/{id}/reply',                    ['as' => 'onlineorder.reply',             'uses' => 'OnlineorderController@reply']);
    Route::post('admin/onlineorder/{id}/mail',                 ['as' => 'onlineorder.mail',           'uses' => 'OnlineorderController@mail']);
    Route::get('admin/onlineorder/{id}/edit',              ['as' => 'onlineorder.edit',            'uses' => 'OnlineorderController@edit']);
    Route::get('admin/onlineorder',                        ['as' => 'onlineorder.index',           'uses' => 'OnlineorderController@index']);
    Route::get('admin/onlineorder/{id}/update', ['as' => 'onlineorder.update', 'uses' => 'OnlineorderController@update']);
    Route::get('admin/onlineorder/{id}/delete',           ['as' => 'onlineorder.delete',          'uses' => 'OnlineorderController@delete']);

    Route::get('admin/menu',                        ['as' => 'menu.index',           'uses' => 'MenuController@index']);
    Route::post('admin/menu/search',                        ['as' => 'menu.search',           'uses' => 'MenuController@search']);
    Route::get('admin/menu/add',                    ['as' => 'menu.add',             'uses' => 'MenuController@add']);
    Route::post('admin/menu/store',                 ['as' => 'menu.store',           'uses' => 'MenuController@store']);
    Route::get('admin/menu/{id}/edit',              ['as' => 'menu.edit',            'uses' => 'MenuController@edit']);
    Route::post('admin/menu/{id}/update',          ['as' => 'menu.update',          'uses' => 'MenuController@update']);
    Route::get('admin/menu/{id}/delete',           ['as' => 'menu.delete',          'uses' => 'MenuController@delete']);
    Route::get('admin/menu/{slug}',           ['as' => 'admin.menu',          'uses' => 'MenuController@menu']);
    Route::get('admin/menu/submenu/{slug}',           ['as' => 'admin.menu.submenu',          'uses' => 'MenuController@menuSubmenu']);

    Route::get('admin/page',                        ['as' => 'page.index',           'uses' => 'PageController@index']);
    Route::get('admin/page/add',                    ['as' => 'page.add',             'uses' => 'PageController@add']);

mediascape/old/app/Models/Principle.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Principle extends Model
{
    protected $table = 'principle';

    // protected $timestamp = false;

    protected $guarded = [];

    protected $fillable = ['title', 'image', 'slug', 'message', 'status'];




}

mediascape/old/app/Http/Controllers/Admin/PrincipleController.php
<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 11/15/16
 * Time: 7:29 AM
 */
namespace App\Http\Controllers\Admin;
use App\Http\Requests\Principle\AddValidation;
use App\Http\Requests\Principle\EditValidation;
use App\Models\Principle;
use Illuminate\Http\Request;


class PrincipleController extends AdminBaseController
{
    protected $base_route = 'admin.principle';
    protected $view_path = 'admin.principle';
    protected $view_title = 'Principle Manger';
    protected $folder_name = 'principle';
    protected $trans_path = 'banner';
    protected $folder_path;

    public function __construct()
    {
        $this->folder_path = public_path().DIRECTORY_SEPARATOR.'images'.DIRECTORY_SEPARATOR.$this->folder_name.DIRECTORY_SEPARATOR;
    }

    public function add(Request $request)
    {

        $data = [];
        $data['row'] = Principle::select()->first();

        return view(parent::loadDefaultVars($this->view_path.'.add'), compact('data'));
    }

    public function update(EditValidation $request, $id)
    {

        if ($request->hasFile('image')){
            $image = $request->file('image');
            $file_name = rand(0000 , 9999) . '_' . $image->getClientOriginalName();
            $image->move($this->folder_path,$file_name);
        }else{
            $file_name = $request->get('oldimg');
        }

        if (!$listing = Principle::find($id)){
            $list = Principle::create([
                'title'               =>     $request->get('title'),
                'slug'               =>     str_slug($request->get('title')),
                'image'                =>    $file_name,
                'message'          =>     $request->get('message'),
                'status' => $request->get('status'),
            ]);
        }else{
            $listing->update([
                'title'               =>     $request->get('title'),
                'slug'               =>     str_slug($request->get('title')),
                'image'                =>    $file_name,
                'message'          =>     $request->get('message'),
                'status' => $request->get('status'),
            ]);
        }

        $request->session()->flash('message', 'Principle updated successfully.');
        return redirect()->route($this->base_route.'.add');
    }



}

mediascape/old/resources/views/admin/principle/partials/breadcrumb.blade.php
<ul class="breadcrumb">
    <li>
        <i class="icon-home home-icon"></i>
        <a href="{{ route('admin.dashboard') }}">{{ trans('general.home') }}</a>
    </li>

    <li>
        <a href="{{ route($base_route.'.add') }}">{{ $view_title }} </a>
    </li>

    @if (isset($data))
        <li class="active">{{ trans($trans_path.'content.common.edit') }} </li>
    @else
        <li class="active">{{ trans($trans_path.'content.common.add') }} </li>
    @endif

</ul><!-- .breadcrumb -->

mediascape/old/resources/views/admin/principle/partials/form.blade.php
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<div class="space-4"></div>


<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="title"> Title </label>

    <div class="col-sm-9">
        <input type="text" name="title" id="title" value="{{ ViewHelper::getData('title', isset($data['row'])?$data['row']:[]) }}" placeholder="Title" class="col-xs-10 col-sm-5">
    </div>
</div>
<div class="space-4"></div>

@if(isset($data['row']))

    <div class="form-group">
        <label class="col-sm-3 control-label no-padding-right" for="image"> Old Image </label>

        <lable class="col-sm-9">

            <img src="{{ asset('images/principle/'.$data['row']['image']) }}" width="200px" for="image" alt="">
        </lable>
    </div>
    <div class="space-4"></div>

    <input type="hidden" value="{{ $data['row']['image'] }}" name="oldimg">
    @endif
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="image"> Image </label>

    <div class="col-sm-9">
        <input type="file" name="image" id="image" value="{{ ViewHelper::getData('image', isset($data['row'])?$data['row']:[]) }}" placeholder="Image" class="col-xs-10 col-sm-5">
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="message"> Principle's Message </label>

    <div class="col-sm-9">
        <textarea name="message" id="message" placeholder="Principle's Message" class="col-xs-10 col-sm-5">{{ ViewHelper::getData('message', isset($data['row'])?$data['row']:[]) }}</textarea>
        <script>
            CKEDITOR.replace( 'description', {
                filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
                filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
                filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
                filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
            });
        </script>
    </div>
</div>
<div class="space-4"></div>

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right" for="status"> Status </label>

    <div class="col-sm-9">
        <div class="radio">
            <label>
                <input name="status" value="1" checked type="radio" class="ace">
                <span class="lbl"> Active</span>
            </label>
        </div>
        <div class="radio">
            <label>
                <input name="status" value="0" type="radio" class="ace">
                <span class="lbl"> In-active</span>
            </label>
        </div>
    </div>
</div>
<div class="space-4"></div>